In [2]:
import torch
torch.cuda.is_available()

True

In [4]:
x = torch.empty(5, 3)
x

tensor([[2.1347e-07, 3.1369e+27, 7.0800e+31],
        [3.1095e-18, 1.8590e+34, 7.7767e+31],
        [7.1536e+22, 3.3803e-18, 1.9421e+31],
        [2.7491e+20, 6.1949e-04, 7.1856e+22],
        [4.3605e+27, 2.3329e-18, 1.9284e+31]])

In [8]:
x = torch.rand(5,3)
x

tensor([[0.0121, 0.1151, 0.3567],
        [0.3495, 0.7534, 0.1391],
        [0.7916, 0.2112, 0.3328],
        [0.3173, 0.2735, 0.3764],
        [0.7699, 0.3235, 0.7548]])

In [10]:
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [11]:
x = x.new_ones(5, 3, dtype=torch.double) 
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

### Gradients

In [40]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
y.grad_fn
z = y * y * 3
print(z)
out = z.mean()
print(out)
out.backward()
x.grad

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [3]:
a = torch.ones(3, 1, requires_grad=True)   # this becomes a placeholder variable
y = a*a + 2      # tracked + 2 has been added to a
print(y)
y.backward(torch.tensor([[3.0], [2.0], [3.0]]), retain_graph=True)   # this becomes the input vector for the differentiation
print(a.grad)

tensor([[3.],
        [3.],
        [3.]], grad_fn=<AddBackward0>)
tensor([[6.],
        [4.],
        [6.]])


device(type='cuda', index=0)